prospecto-develop/prospecto-develop/Prospecto.ViewMvc/Controllers/BranchController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Prospecto.Models.DTO;
using Prospecto.Models.Enums;
using Prospecto.Models.ViewModel;
using Prospecto.Service.Interface;
using Prospecto.ViewMvc.Models;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Prospecto.ViewMvc.Controllers
{
    public class BranchController : ProspectoControllerBase
    {
        private readonly ILogger<BranchController> _logger;
        private readonly IBranchService _branchService;
        private readonly IMapper _mapper;
        private readonly ICompanyService _companyService;

        private readonly string Title = "Filial";
        private readonly string Message = "Preencha os dados da filial para realizar o cadastro!";

        public BranchController(
            IMapper mapper,
            IBranchService branchService,
            ICompanyService companyService,
            ILogger<BranchController> logger)
        {

            _logger = logger;
            _branchService = branchService;
            _mapper = mapper;
            _companyService = companyService;
        }

        public IActionResult Index(int? Id)
        {
            var obj = LoadIndex(Id);
            return View(obj);
        }

        public IActionResult List()
        {
            GetContextData();
            BranchFiltersViewModel filters = new();

            if (Role == UserTypeEnum.MANAGER.ToString()) filters.IdCompany = CompanyId;

            ViewData["Title"] = Title;
            var obj = _branchService.ListByFilters(filters);
            return View(obj);
        }

        public IActionResult ListPartial()
        {
            GetContextData();
            BranchFiltersViewModel filters = new();

            if (Role == UserTypeEnum.MANAGER.ToString()) filters.IdCompany = CompanyId;

            ViewData["Title"] = Title;
            var obj = _branchService.ListByFilters(filters);
            return PartialView(obj);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(BranchViewModel brancheViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var dto = _mapper.Map<BranchDTO>(brancheViewModel);
                    if (brancheViewModel.Id > 0)
                    {
                        TempData["success"] = "Filial atualizada com sucesso!";
                        await _branchService.Update(brancheViewModel.Id, dto);
                    }
                    else
                    {
                        TempData["success"] = "Filial inserida com sucesso!";
                        await _branchService.Insert(dto);
                    }

                    TempData["success"] = "Filial salvo com sucesso!";
                    return RedirectToAction("List");
                }
                else
                {
                    var obj = LoadIndex(brancheViewModel.Id);
                    return View("Index", obj);
                }
            }
            catch (System.Exception)
            {
                return RedirectToAction("Error", "Shared");
            }
        }

        private BranchViewModel LoadIndex(int? Id)
        {
            GetContextData();

            ViewData["Title"] = Title;
            ViewData["Message"] = Message;

            var obj = new BranchViewModel();
            if (Id > 0)
            {
                var _infoResult = _branchService.Get(Id.Value).Result;
                if (_infoResult.Success && _infoResult.Value != null)
                {
                    obj = _infoResult.Value.AsBranchViewMode();
                }
            }


            CompanyFiltersViewModel filters = new();

            if (Role == UserTypeEnum.MANAGER.ToString()) filters.Id = CompanyId;

            IList<SelectListItem> listCompany = new List<SelectListItem>();

            foreach (var item in _companyService.ListByFilters(filters))
            {
                listCompany.Add(new SelectListItem { Value = item.Id.ToString(), Text = item.Description, Selected = item.Id == obj.CompanyId });
            }
            ViewBag.ListCompany = listCompany;

            return obj;
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

prospecto-develop/prospecto-develop/Prospecto.ViewMvc/Views/Branch/Index.cshtml
@model Prospecto.Models.ViewModel.BranchViewModel

@using (Html.BeginForm("Save", "Branch", FormMethod.Post, new { role = "form" }))
{
    <section class="content-header">
        <h1>
            @ViewData["Title"]
            <small>@ViewData["Message"]</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Filial</li>
        </ol>
    </section>
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-body">
                        <input type="hidden" id="Id" name="Id" value="@Model.Id">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>ID</label>
                                    <input type="text" class="form-control" id="id" asp-for="Id" readonly placeholder="Id" value="@Model.Id.ToString("0000")">
                                    <span class="glyphicon glyphicon-remove form-control input-sm-feedback" style="display: none"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="example-email">Descrição <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="description" asp-for="Description" placeholder="Descrição">
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label asp-for="SalesGoal">Meta <span style="color: red">*</span></label>
                                    <input type="text" class="form-control" id="salesGoal" asp-for="SalesGoal" name="SalesGoal" placeholder="0,00">                                    
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="CompanyId">Empresa <span class="text-danger">*</span></label>
                                    <select asp-for="CompanyId" name="CompanyId" id="CompanyId" asp-items="ViewBag.ListCompany" class="form-control input select2">
                                    </select>
                                    <span asp-validation-for="CompanyId" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-md-2 pull-left" style="margin: 10px 0;">
                                <a href="@Url.Action("List", "Branch")" class="btn btn-default col-md-12" data-loading-text="Cancelar...">&nbsp;Cancelar</a>
                            </div>

                            <div class="col-md-2 pull-right" style="margin: 10px 0;">
                                <button type="submit" class="btn btn-primary col-md-12">Salvar</button>
                            </div>

                        </div>

                    </div>
                </div>
                @Html.AntiForgeryToken()
            </div>
            <!-- Column -->
        </div>
    </section>
    @section Scripts{
        <script>
            $('#salesGoal').autoNumeric('init', {
                aSep: '.',
                aDec: ',',
                vMax: '9999999999.99',
                mDec: '2',
                vMin: '000'
            });
        </script>
    }
}

prospecto-develop/prospecto-develop/Prospecto.ViewMvc/Views/Branch/List.cshtml
<section class="content-header">
    <h1>
        @ViewData["Title"]
        <small>@ViewData["Message"]</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Filial</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-body">
                    <div class="col-sm-12">
                        <div class="col-xs-12">
                            <div class="btn-toolbar" role="toolbar">
                                <div class="btn-group pull-right">
                                    <a class="btn btn-primary" href="@Url.Action("Index", "Branch")" id="BotaoCriar"><span class="fa fa-plus"></span>&nbsp;Adicionar</a>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div id="listGrid" class="row">
                            @{
                                await Html.RenderPartialAsync("ListPartial");
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{

    <script>
        $('#tableBranch').DataTable({
            dom: "Bfrtip",
            buttons: [{
                extend: "excel",
                className: "btn-sm",
                text: 'Excel',
            }],
            'paging': true,
            'lengthChange': false,
            'searching': false,
            'ordering': true,
            'info': true,
            'autoWidth': false,
            "oLanguage": {
                "sLengthMenu": 'Mostrar <select><option value="50">50</option><option value="100">100</option><option value="200">200</option><option value="300">300</option><option value="500">500</option><option value="-1">Todos</option></select> registros.',
                "sSearch": "Pesquisar:",
                "sInfo": "Exibindo (_START_ de _END_) do(s) _TOTAL_ registro(s).",
                "sZeroRecords": "Nenhum registro econtrado.",
                "oPaginate": {
                    "sLast": "Última Página",
                    "sFirst": "Primeira Página",
                    "sNext": "Próxima",
                    "sPrevious": "Anterior"
                }
            }
        })

        $("#tableBranch tbody tr").on("dblclick", function (event) {
            var id = this.cells[0].id;
            window.location.href = "@Url.Action("Index", "Branch")?Id="+id+"";
        });
    </script>
}

prospecto-develop/prospecto-develop/Prospecto.ViewMvc/Views/Branch/ListPartial.cshtml
@model IEnumerable<Prospecto.Models.ViewModel.BranchViewModel>


<div class="adv-table">
    <table id="tableBranch" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Código</th>
                <th>Descrição</th>
                <th>Empresa</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr style="cursor: pointer">
                <td id="@item.Id" style="width: 5%">  @item.Id.ToString("0000") </td>
                <td style="width: 30%"> @item.Description </td>
                <td style="width: 30%"> @item.Company?.Description </td>
                <td style="width: 5%">
                    <div class="text-center">
                        <a class="fa fa-pencil" title="Editar" data-id="@item.Id" style="font-size: 16px; color: #75798B" href="@Url.Action("Index", "Branch", new { Id = item.Id })"></a>
                        @*<a class="fa fa-remove" title="Excluir" data-id="@item.Id" style="font-size: 16px; color: #75798B" onclick="Excluir($(this))"></a>*@
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>